#!/usr/bin/env bash
# ponytail: confluence export with macros, image uploads, parent-child hierarchy, and robust XHTML parsing.
set -euo pipefail

FILE="${1:-}"
SPACE_KEY="${2:-}"
PARENT_ID="${3:-}"

if [[ -z "$FILE" || ! -f "$FILE" || -z "$SPACE_KEY" ]]; then
  echo "Usage: $0 <path-to-markdown-file> <space-key> [parent-page-id]"
  exit 1
fi

if [[ -z "${CONFLUENCE_URL:-}" || -z "${CONFLUENCE_PAT:-}" ]]; then
  echo "Error: Please set CONFLUENCE_URL and CONFLUENCE_PAT environment variables."
  exit 1
fi

TITLE=$(head -n 1 "$FILE" | sed 's/^# *//')
TITLE="${TITLE:-Generated Document $(date +%s)}"

echo "Converting Markdown to HTML..."
RAW_HTML=$(npx --yes marked < "$FILE")

echo "Processing Confluence Macros and Images..."
cat << 'EOF' > process_html.py
import sys, re, html, os, xml.etree.ElementTree as ET

raw_html = sys.stdin.read()

# Fix self-closing void elements for XHTML / Confluence Storage Format
raw_html = re.sub(r'<br\s*>', '<br/>', raw_html)
raw_html = re.sub(r'<hr\s*>', '<hr/>', raw_html)

# Targeted unescape of ac: and ri: tags generated by marked
raw_html = raw_html.replace('&quot;', '"')
raw_html = raw_html.replace('&lt;ac:', '<ac:').replace('&lt;/ac:', '</ac:')
raw_html = raw_html.replace('&lt;ri:', '<ri:').replace('&lt;/ri:', '</ri:')
raw_html = raw_html.replace('&gt;', '>')

# Convert Back to Top / Hash links to native Confluence Anchor Links
def anchor_link_replacer(match):
    anchor_name = match.group(1)
    link_text = match.group(2)
    return f'<ac:link ac:anchor="{anchor_name}"><ac:plain-text-link-body><![CDATA[{link_text}]]></ac:plain-text-link-body></ac:link>'

raw_html = re.sub(r'<a href="#([^"]+)">(.*?)</a>', anchor_link_replacer, raw_html)

# Strip first H1 from rendered HTML body to avoid duplicate title in Confluence
raw_html = re.sub(r'<h1[^>]*>.*?</h1>', '', raw_html, count=1, flags=re.DOTALL)

# Convert Code blocks first
code_pattern = re.compile(r'<pre><code(?: class="language-([^"]+)")?>(.*?)</code></pre>', re.DOTALL)
def code_replacer(match):
    lang = match.group(1) or 'none'
    code_content = match.group(2)
    code_content = html.unescape(code_content)
    code_content = code_content.replace(']]>', ']]]]><![CDATA[>')
    if lang.lower() == 'mermaid':
        if 'sequenceDiagram' in code_content:
            return f'<ac:structured-macro ac:name="mermaiddiagram"><ac:parameter ac:name="" /><ac:plain-text-body><![CDATA[{code_content}]]></ac:plain-text-body></ac:structured-macro>'
        else:
            return f'<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">text</ac:parameter><ac:plain-text-body><![CDATA[{code_content}]]></ac:plain-text-body></ac:structured-macro>'
    return f'<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">{lang}</ac:parameter><ac:plain-text-body><![CDATA[{code_content}]]></ac:plain-text-body></ac:structured-macro>'

processed = code_pattern.sub(code_replacer, raw_html)

# Escape lone ampersands not part of valid XML entities
processed = re.sub(r'&(?!(?:amp|lt|gt|quot|#\d+|#x[0-9a-fA-F]+);)', '&amp;', processed)

# Convert Markdown Checkbox Lists to native Confluence Task Lists
def task_list_replacer(match):
    list_content = match.group(1)
    tasks = []
    task_id = 3001
    for li in re.finditer(r'<li>\s*<input\s+([^>]*?)type="checkbox"[^>]*>(.*?)</li>', list_content, re.DOTALL):
        attrs = li.group(1)
        body = li.group(2).strip()
        status = 'complete' if 'checked' in attrs else 'incomplete'
        tasks.append(f'<ac:task>\n<ac:task-id>{task_id}</ac:task-id>\n<ac:task-status>{status}</ac:task-status>\n<ac:task-body>{body}</ac:task-body>\n</ac:task>')
        task_id += 1
    return '<ac:task-list>\n' + '\n'.join(tasks) + '\n</ac:task-list>'

processed = re.sub(r'<ul>(\s*<li>\s*<input[^>]*type="checkbox".*?</li>\s*)</ul>', task_list_replacer, processed, flags=re.DOTALL)

# Convert blockquotes to Confluence Callout Panel Macros
def bq_replacer_single(match):
    content = match.group(1).strip()
    m = re.match(r'^(?:<p>)?\[!(NOTE|INFO|WARNING|ERROR|TIP|CAUTION|IMPORTANT)\](.*)$', content, re.DOTALL)
    if m:
        alert_type = m.group(1)
        type_map = {
            'NOTE': 'note',
            'INFO': 'info',
            'WARNING': 'warning',
            'ERROR': 'warning',
            'TIP': 'tip',
            'CAUTION': 'warning',
            'IMPORTANT': 'warning'
        }
        ac_name = type_map.get(alert_type, 'info')
        rest = m.group(2).strip()
        if rest.startswith('</p>'): rest = rest[4:].strip()
        parts = re.split(r'(<ac:structured-macro ac:name="code".*?</ac:structured-macro>)', rest, flags=re.DOTALL)
        out_parts = []
        for p in parts:
            p_clean = p.strip()
            if not p_clean: continue
            if p_clean.startswith('<ac:structured-macro'):
                out_parts.append(p_clean)
            elif p_clean.startswith('<ol>') or p_clean.startswith('<ul>') or p_clean.startswith('<p>') or p_clean.startswith('<h'):
                out_parts.append(p_clean)
            else:
                if not p_clean.startswith('<p>'): p_clean = '<p>' + p_clean
                if not p_clean.endswith('</p>'): p_clean = p_clean + '</p>'
                out_parts.append(p_clean)
        rich_body = ''.join(out_parts)
        rich_body = re.sub(r'</ol>\s*</p>', r'</ol>', rich_body)
        rich_body = re.sub(r'</ul>\s*</p>', r'</ul>', rich_body)
        rich_body = re.sub(r'<p>\s*(<ol>|<ul>)', r'\1', rich_body)
        return f'<ac:structured-macro ac:name="{ac_name}"><ac:rich-text-body>{rich_body}</ac:rich-text-body></ac:structured-macro>'
    return match.group(0)

processed = re.sub(r'<blockquote>\s*(.*?)\s*</blockquote>', bq_replacer_single, processed, flags=re.DOTALL)

# Extract images and replace with Confluence image tags
image_pattern = re.compile(r'<img\s+[^>]*src="([^"]+)"[^>]*>')
images = image_pattern.findall(processed)
with open("images_to_upload.txt", "w") as f:
    for img in images:
        f.write(img + "\n")

def image_replacer(match):
    src = match.group(1)
    filename = os.path.basename(src)
    return f'<p><ac:image ac:align="center"><ri:attachment ri:filename="{filename}" /></ac:image></p>'

processed_html = image_pattern.sub(image_replacer, processed)

# Validate XML before sending
root_wrapper = f'<root xmlns:ac="http://www.atlassian.com/schema/confluence/4/ac/" xmlns:ri="http://www.atlassian.com/schema/confluence/4/ri/">{processed_html}</root>'
try:
    ET.fromstring(root_wrapper)
except ET.ParseError as e:
    sys.stderr.write(f"XML Validation Error: {e}\n")
    sys.exit(1)

sys.stdout.write(processed_html)
EOF

HTML_CONTENT=$(python3 process_html.py <<< "$RAW_HTML")

AUTH_HEADER="Authorization: Bearer ${CONFLUENCE_PAT}"
if [[ -n "${CONFLUENCE_EMAIL:-}" ]]; then
  AUTH_B64=$(echo -n "${CONFLUENCE_EMAIL}:${CONFLUENCE_PAT}" | base64)
  AUTH_HEADER="Authorization: Basic ${AUTH_B64}"
fi

# Clean trailing slash from CONFLUENCE_URL
BASE_URL="${CONFLUENCE_URL%/}"
# Support both /rest/api and /wiki/rest/api endpoints
SEARCH_URL="${BASE_URL}/rest/api/content"
if curl -sS -I -H "${AUTH_HEADER}" "${BASE_URL}/rest/api/content" 2>&1 | grep -q "404"; then
  SEARCH_URL="${BASE_URL}/wiki/rest/api/content"
fi

echo "Checking if page '$TITLE' already exists in space '$SPACE_KEY'..."
EXISTING_RESP=$(curl -sS -G "${SEARCH_URL}" \
  -H "${AUTH_HEADER}" \
  --data-urlencode "title=${TITLE}" \
  --data-urlencode "spaceKey=${SPACE_KEY}" \
  --data-urlencode "expand=version")

EXISTING_ID=$(echo "$EXISTING_RESP" | jq -r '.results[0].id // empty')

if [[ -n "$EXISTING_ID" ]]; then
  EXISTING_VER=$(echo "$EXISTING_RESP" | jq -r '.results[0].version.number // 1')
  NEW_VER=$((EXISTING_VER + 1))
  echo "Found existing page ID: $EXISTING_ID (Version $EXISTING_VER). Bumping to Version $NEW_VER..."

  PAYLOAD=$(jq -n \
    --arg title "$TITLE" \
    --arg space "$SPACE_KEY" \
    --arg html "$HTML_CONTENT" \
    --argjson ver "$NEW_VER" \
    '{
      type: "page",
      title: $title,
      space: { key: $space },
      version: { number: $ver },
      body: {
        storage: { value: $html, representation: "storage" }
      }
    }')

  RESPONSE=$(curl -sS -X PUT "${SEARCH_URL}/${EXISTING_ID}" \
    -H "${AUTH_HEADER}" \
    -H "Content-Type: application/json" \
    -d "$PAYLOAD")

  PAGE_ID=$(echo "$RESPONSE" | jq -r '.id // empty')
else
  echo "Creating new Confluence page '$TITLE' in space '$SPACE_KEY'..."
  PAYLOAD=$(jq -n \
    --arg title "$TITLE" \
    --arg space "$SPACE_KEY" \
    --arg html "$HTML_CONTENT" \
    '{
      type: "page",
      title: $title,
      space: { key: $space },
      body: {
        storage: { value: $html, representation: "storage" }
      }
    }')

  if [[ -n "$PARENT_ID" ]]; then
    PAYLOAD=$(echo "$PAYLOAD" | jq --argjson anc '[{"id": "'"${PARENT_ID}"'"}]' '. + {ancestors: $anc}')
  fi

  RESPONSE=$(curl -sS -X POST "${SEARCH_URL}" \
    -H "${AUTH_HEADER}" \
    -H "Content-Type: application/json" \
    -d "$PAYLOAD")

  PAGE_ID=$(echo "$RESPONSE" | jq -r '.id // empty')
fi

if [[ -z "$PAGE_ID" ]]; then
  echo "Failed to publish page. Response:"
  echo "$RESPONSE" | jq .
  exit 1
fi

echo "Successfully published page! Page ID: $PAGE_ID"

# Upload attachments
if [[ -f "images_to_upload.txt" ]]; then
  while read -r IMG_PATH; do
    if [[ -n "$IMG_PATH" && -f "$IMG_PATH" ]]; then
      echo "Uploading attachment: $IMG_PATH"
      curl -sS -X POST "${SEARCH_URL}/${PAGE_ID}/child/attachment" \
        -H "${AUTH_HEADER}" \
        -H "X-Atlassian-Token: nocheck" \
        -F "file=@${IMG_PATH}" > /dev/null || true
    else
      echo "Warning: Image not found at path '$IMG_PATH', skipping attachment upload."
    fi
  done < images_to_upload.txt
fi

# Cleanup
rm -f process_html.py images_to_upload.txt

echo
echo "Done! Published Page ID is: $PAGE_ID"
