#!/usr/bin/env bash
# ponytail: simplest gist creation using gh cli. Add --public if needed.
set -euo pipefail

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 <path-to-markdown-file> [additional-files...]"
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "Error: gh CLI is not installed."
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "Error: You are not authenticated with GitHub. Please run 'gh auth login' first."
  exit 1
fi

echo "Creating GitHub Gist with $# file(s)..."
gh gist create "$@" --desc "Generated by Scribe Skill"
